<script setup lang="ts">
import AppDataTable from '@/components/AppDataTable.vue';
import type { User } from '@/interfaces/dataTable.interface';
import { ref } from 'vue';
const tableData = ref<User[]>([
  {
    id: 1,
    usuarioNombre: 'Leanne Graham',
    usuarioApellidoPaterno: 'Bret',
    usuarioApellidoMaterno: 'Bret',
    usuarioEmail: 'leanne@gmail.com',
    usuarioTelefono: '1-770-736-8031 x56442',
  },
  {
    id: 2,
    usuarioNombre: 'Ervin Howell',
    usuarioApellidoPaterno: 'Antonette',
    usuarioApellidoMaterno: 'Antonette',
    usuarioEmail: 'ervin@gmail.com',
    usuarioTelefono: '010-692-6593 x09125',
  },
  {
    id: 3,
    usuarioNombre: 'Clementine Bauch',
    usuarioApellidoPaterno: 'Samantha',
    usuarioApellidoMaterno: 'Samantha',
    usuarioEmail: 'clementine@gmail.com',
    usuarioTelefono: '1-463-123-4447',
  },
  {
    id: 4,
    usuarioNombre: 'Patricia Lebsack',
    usuarioApellidoPaterno: 'Karianne',
    usuarioApellidoMaterno: 'Karianne',
    usuarioEmail: 'patricia@gmail.com',
    usuarioTelefono: '493-170-9623 x156',
  },
  {
    id: 5,
    usuarioNombre: 'Arnaldo Lebsack',
    usuarioApellidoPaterno: 'asd',
    usuarioApellidoMaterno: 'Karianne',
    usuarioEmail: 'arnaldo@gmail.com',
    usuarioTelefono: '493-170-9623 x156',
  },
  {
    id: 6,
    usuarioNombre: 'Ruben Lebsack',
    usuarioApellidoPaterno: 'Karianne',
    usuarioApellidoMaterno: 'Karianne',
    usuarioEmail: 'ruben@gmail.com',
    usuarioTelefono: '493-170-9623 x156',
  },
  {
    id: 7,
    usuarioNombre: 'Miguel Lebsack',
    usuarioApellidoPaterno: 'Karianne',
    usuarioApellidoMaterno: 'Karianne',
    usuarioEmail: 'miguel@gmail.com',
    usuarioTelefono: '493-170-9623 x156',
  },
  {
    id: 8,
    usuarioNombre: 'Patricia Lebsack',
    usuarioApellidoPaterno: 'Karianne',
    usuarioApellidoMaterno: 'Karianne',
    usuarioEmail: 'patricia2@gmail.com',
    usuarioTelefono: '493-170-9623 x156',
  },
  {
    id: 9,
    usuarioNombre: 'Juan Perez',
    usuarioApellidoPaterno: 'Gomez',
    usuarioApellidoMaterno: 'Lopez',
    usuarioEmail: 'juan@gmail.com',
    usuarioTelefono: '123-456-7890',
  },
  {
    id: 10,
    usuarioNombre: 'Maria Garcia',
    usuarioApellidoPaterno: 'Fernandez',
    usuarioApellidoMaterno: 'Martinez',
    usuarioEmail: 'maria@gmail.com',
    usuarioTelefono: '234-567-8901',
  },
  {
    id: 11,
    usuarioNombre: 'Carlos Sanchez',
    usuarioApellidoPaterno: 'Rodriguez',
    usuarioApellidoMaterno: 'Hernandez',
    usuarioEmail: 'carlos@gmail.com',
    usuarioTelefono: '345-678-9012',
  },
  {
    id: 12,
    usuarioNombre: 'Ana Lopez',
    usuarioApellidoPaterno: 'Diaz',
    usuarioApellidoMaterno: 'Gutierrez',
    usuarioEmail: 'ana@gmail.com',
    usuarioTelefono: '456-789-0123',
  },
  {
    id: 13,
    usuarioNombre: 'Luis Torres',
    usuarioApellidoPaterno: 'Ramirez',
    usuarioApellidoMaterno: 'Vargas',
    usuarioEmail: 'luis@gmail.com',
    usuarioTelefono: '567-890-1234',
  },
  {
    id: 14,
    usuarioNombre: 'Sofia Ramirez',
    usuarioApellidoPaterno: 'Morales',
    usuarioApellidoMaterno: 'Castro',
    usuarioEmail: 'sofia@gmail.com',
    usuarioTelefono: '678-901-2345',
  },
  {
    id: 15,
    usuarioNombre: 'Jorge Castro',
    usuarioApellidoPaterno: 'Ortega',
    usuarioApellidoMaterno: 'Rojas',
    usuarioEmail: 'jorge@gmail.com',
    usuarioTelefono: '789-012-3456',
  },
  {
    id: 16,
    usuarioNombre: 'Lucia Rojas',
    usuarioApellidoPaterno: 'Silva',
    usuarioApellidoMaterno: 'Mendoza',
    usuarioEmail: 'lucia@gmail.com',
    usuarioTelefono: '890-123-4567',
  },
  {
    id: 17,
    usuarioNombre: 'Pedro Mendoza',
    usuarioApellidoPaterno: 'Carrillo',
    usuarioApellidoMaterno: 'Guerrero',
    usuarioEmail: 'pedro@gmail.com',
    usuarioTelefono: '901-234-5678',
  },
  {
    id: 18,
    usuarioNombre: 'Carmen Guerrero',
    usuarioApellidoPaterno: 'Vega',
    usuarioApellidoMaterno: 'Fuentes',
    usuarioEmail: 'carmen@gmail.com',
    usuarioTelefono: '012-345-6789',
  },
  {
    id: 19,
    usuarioNombre: 'Ricardo Fuentes',
    usuarioApellidoPaterno: 'Mendez',
    usuarioApellidoMaterno: 'Rios',
    usuarioEmail: 'ricardo@gmail.com',
    usuarioTelefono: '123-456-7890',
  },
  {
    id: 20,
    usuarioNombre: 'Elena Rios',
    usuarioApellidoPaterno: 'Paredes',
    usuarioApellidoMaterno: 'Navarro',
    usuarioEmail: 'elena@gmail.com',
    usuarioTelefono: '234-567-8901',
  },
  {
    id: 21,
    usuarioNombre: 'Fernando Navarro',
    usuarioApellidoPaterno: 'Cortes',
    usuarioApellidoMaterno: 'Miranda',
    usuarioEmail: 'fernando@gmail.com',
    usuarioTelefono: '345-678-9012',
  },
  {
    id: 22,
    usuarioNombre: 'Isabel Miranda',
    usuarioApellidoPaterno: 'Soto',
    usuarioApellidoMaterno: 'Cardenas',
    usuarioEmail: 'isabel@gmail.com',
    usuarioTelefono: '456-789-0123',
  },
  {
    id: 23,
    usuarioNombre: 'Oscar Cardenas',
    usuarioApellidoPaterno: 'Campos',
    usuarioApellidoMaterno: 'Aguilar',
    usuarioEmail: 'oscar@gmail.com',
    usuarioTelefono: '567-890-1234',
  },
  {
    id: 24,
    usuarioNombre: 'Adriana Aguilar',
    usuarioApellidoPaterno: 'Valdez',
    usuarioApellidoMaterno: 'Reyes',
    usuarioEmail: 'adriana@gmail.com',
    usuarioTelefono: '678-901-2345',
  },
  {
    id: 25,
    usuarioNombre: 'Raul Reyes',
    usuarioApellidoPaterno: 'Orozco',
    usuarioApellidoMaterno: 'Soria',
    usuarioEmail: 'raul@gmail.com',
    usuarioTelefono: '789-012-3456',
  },
  {
    id: 26,
    usuarioNombre: 'Gabriela Soria',
    usuarioApellidoPaterno: 'Mejia',
    usuarioApellidoMaterno: 'Espinoza',
    usuarioEmail: 'gabriela@gmail.com',
    usuarioTelefono: '890-123-4567',
  },
  {
    id: 27,
    usuarioNombre: 'Hector Espinoza',
    usuarioApellidoPaterno: 'Nunez',
    usuarioApellidoMaterno: 'Delgado',
    usuarioEmail: 'hector@gmail.com',
    usuarioTelefono: '901-234-5678',
  },
  {
    id: 28,
    usuarioNombre: 'Monica Delgado',
    usuarioApellidoPaterno: 'Salazar',
    usuarioApellidoMaterno: 'Cruz',
    usuarioEmail: 'monica@gmail.com',
    usuarioTelefono: '012-345-6789',
  },
  {
    id: 29,
    usuarioNombre: 'Roberto Cruz',
    usuarioApellidoPaterno: 'Ibarra',
    usuarioApellidoMaterno: 'Lara',
    usuarioEmail: 'roberto@gmail.com',
    usuarioTelefono: '123-456-7890',
  },
  {
    id: 30,
    usuarioNombre: 'Laura Lara',
    usuarioApellidoPaterno: 'Mora',
    usuarioApellidoMaterno: 'Flores',
    usuarioEmail: 'laura@gmail.com',
    usuarioTelefono: '234-567-8901',
  },
]);
</script>

<template>
  <main>
    <AppDataTable :data="tableData" />
  </main>
</template>
